Update setup guides for backend and components, take 2
BobaBoard/boba-docs pull request #65
Opened 2023-07-07 20:19 UTC by riazaia

Made a whole new branch with lots of hope in my heart.

https://github.com/BobaBoard/boba-docs/pull/60 again.

2023-07-25 03:02 UTC, essential-randomness commented
Removing myself and throwing @enigmalea under the bus

2023-08-12 21:30 UTC, enigmalea requested changes

2023-08-12 21:30 UTC, enigmalea commented on docusaurus/docs/engineering/start-developing/boba-backend.md
should we... mention that you should cd into the folder where you store your projects before you clone?

2023-08-12 21:30 UTC, enigmalea commented on docusaurus/docs/engineering/start-developing/boba-backend.md
> +:::
Not going to comment this on every admoniition, but as an FYI for prettier to not body your admonitions they need empty lines around them and the content like so:

```suggestion
:::tip

The commands shown on this page use HTTPS to interact with the code on GitHub but you can do so with SSH if you're comfortable

:::
```

2023-08-15 21:29 UTC, enigmalea approved these changes

2023-08-15 21:30 UTC, merged